name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - cobra
    - cameo
    - pytest
    - sklearn
    - pandas
    - altair
    - tqdm
    - networkx
    - matplotlib
