name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sklearn
  - pandas
  - altair
  - tqdm
  - networkx
  - matplotlib
  - pip
  - pip:
    - cobra
    - cameo
    - pytest